package admin

import "github.com/gin-gonic/gin"

// RegisterRoutes 注册 /api/admin 管理员路由（需要 JWT + Admin 认证）
func RegisterRoutes(group *gin.RouterGroup) {
	group.GET("/unified-gateway/overview", UnifiedGatewayOverview)
	group.GET("/unified-gateway/channels", UnifiedChannels)
	group.POST("/unified-gateway/channels", CreateUnifiedChannel)
	group.PUT("/unified-gateway/channels/:id", UpdateUnifiedChannel)
	group.GET("/unified-gateway/channels/:id/pools", UnifiedChannelPools)
	group.POST("/unified-gateway/channels/:id/pools", CreateUnifiedChannelPool)
	group.PUT("/unified-gateway/pools/:id", UpdateUnifiedPool)
	group.POST("/unified-gateway/pools/:id/status", TransitionUnifiedPool)
	group.GET("/unified-gateway/catalog", UnifiedGatewayCatalog)
	group.POST("/unified-gateway/catalog", CreateUnifiedCatalogDraft)
	group.GET("/unified-gateway/catalog-sources", ListUnifiedCatalogSources)
	group.GET("/unified-gateway/catalog-sources/options", UnifiedCatalogSourceOptions)
	group.POST("/unified-gateway/catalog-sources", CreateUnifiedCatalogSource)
	group.POST("/unified-gateway/catalog-sources/:source_id/status", TransitionUnifiedCatalogSource)
	group.GET("/unified-gateway/catalog/:id", GetUnifiedCatalogRelease)
	group.GET("/unified-gateway/catalog/:id/discoveries", ListUnifiedCatalogDiscoveries)
	group.POST("/unified-gateway/catalog/:id/catalog-sources/:source_id/discover", ScheduleUnifiedCatalogDiscovery)
	group.GET("/unified-gateway/catalog-discoveries/:snapshot_id/items", ListUnifiedCatalogDiscoveryItems)
	group.POST("/unified-gateway/catalog-discoveries/:snapshot_id/review", ReviewUnifiedCatalogDiscovery)
	group.GET("/unified-gateway/catalog/:id/price-candidates", ListUnifiedCatalogPriceCandidates)
	group.POST("/unified-gateway/catalog-price-candidates/:candidate_id/review", ReviewUnifiedCatalogPriceCandidate)
	group.GET("/unified-gateway/catalog/:id/options", UnifiedCatalogOptions)
	group.GET("/unified-gateway/catalog/:id/skus", ListUnifiedCatalogSKUs)
	group.POST("/unified-gateway/catalog/:id/skus", CreateUnifiedCatalogSKU)
	group.DELETE("/unified-gateway/catalog/:id/skus/:sku_id", DeleteUnifiedCatalogSKU)
	group.GET("/unified-gateway/catalog/:id/products", ListUnifiedCatalogProducts)
	group.POST("/unified-gateway/catalog/:id/products", CreateUnifiedCatalogProduct)
	group.DELETE("/unified-gateway/catalog/:id/products/:product_id", DeleteUnifiedCatalogProduct)
	group.GET("/unified-gateway/catalog/:id/rates", ListUnifiedCatalogRates)
	group.POST("/unified-gateway/catalog/:id/rates/:kind", CreateUnifiedCatalogRate)
	group.DELETE("/unified-gateway/catalog/:id/rates/:kind/:rate_id", DeleteUnifiedCatalogRate)
	group.POST("/unified-gateway/catalog/:id/publish", UnifiedGatewayPublishCatalog)
	group.POST("/unified-gateway/catalog/:id/retire", UnifiedGatewayRetireCatalog)
	group.POST("/unified-gateway/catalog/:id/activate", ActivateUnifiedCatalog)
	group.POST("/unified-gateway/deployments", CreateUnifiedDeployment)
	group.GET("/unified-gateway/deployments", ListUnifiedDeployments)
	group.GET("/unified-gateway/deployments/runtime-identity", UnifiedDeploymentIdentity)
	group.POST("/unified-gateway/deployments/:id/members", AddUnifiedDeploymentMember)
	group.POST("/unified-gateway/deployments/:id/prove-current", ProveCurrentUnifiedDeployment)
	group.POST("/unified-gateway/deployments/:id/members/:member_id/catalog-readiness", RecordUnifiedCatalogReadiness)
	group.POST("/unified-gateway/deployments/:id/members/:member_id/crypto-readiness", RecordUnifiedCryptoReadiness)
	group.POST("/unified-gateway/deployments/:id/activate", ActivateUnifiedDeployment)
	group.GET("/unified-gateway/credentials", UnifiedGatewayCredentials)
	group.GET("/unified-gateway/currencies", ListUnifiedCurrencies)
	group.POST("/unified-gateway/currencies", CreateUnifiedCurrency)
	group.POST("/unified-gateway/currencies/:code/activate", ActivateUnifiedCurrency)
	group.GET("/unified-gateway/rate-evidence", ListUnifiedRateEvidence)
	group.POST("/unified-gateway/rate-evidence", CreateUnifiedRateEvidence)
	group.POST("/unified-gateway/rate-evidence/:id/review", ReviewUnifiedRateEvidence)
	group.POST("/unified-gateway/pools/:id/credentials", CreateUnifiedCredential)
	group.PUT("/unified-gateway/credentials/:id", UpdateUnifiedCredential)
	group.POST("/unified-gateway/credentials/:id/status", TransitionUnifiedCredential)
	group.POST("/unified-gateway/offerings/:offering_id/credentials/:credential_id/validations/:kind", RecordUnifiedOfferingValidation)
	group.GET("/unified-gateway/calls", UnifiedGatewayCalls)
	group.GET("/unified-gateway/calls/:id", UnifiedGatewayCallDetail)
	group.GET("/unified-gateway/calls/:id/requests", UnifiedCallRequestLogs)
	group.GET("/unified-gateway/calls/:id/requests/:request_id/payloads", UnifiedRequestLogPayloads)
	// 用户管理
	group.GET("/users", ListUsers)
	group.PUT("/users/:id/role", UpdateUserRole)
	group.PUT("/users/:id/status", UpdateUserStatus)
	group.POST("/users/:id/recharge", RechargeUser)

	// 视频任务是统一调用资源的只读投影。
	vid := group.Group("/video")
	{
		vid.GET("/tasks", ListUnifiedVideoTasks)
		vid.GET("/tasks/:id", GetUnifiedVideoTask)
		vid.GET("/stats", GetUnifiedVideoStats)
	}
}
