-- Reason: introduce one durable ledger record per downstream API call and one
-- attempt record per concrete upstream execution.
-- Requirement: correlate users, tokens, retries, usage, billing, retained
-- payloads, asynchronous resources, and playground conversations.
-- Impact: creates the ledger tables only. Existing-table references and
-- deterministic history backfill are handled by later ordered migrations.

CREATE TABLE IF NOT EXISTS api_calls (
    id VARCHAR(64) NOT NULL,
    request_id VARCHAR(128) NOT NULL DEFAULT '',
    user_id BIGINT UNSIGNED NOT NULL,
    token_id BIGINT UNSIGNED NOT NULL,
    endpoint VARCHAR(255) NOT NULL DEFAULT '',
    operation VARCHAR(32) NOT NULL DEFAULT '',
    model VARCHAR(80) NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'received',
    is_stream TINYINT(1) NOT NULL DEFAULT 0,
    background TINYINT(1) NOT NULL DEFAULT 0,
    store TINYINT(1) NOT NULL DEFAULT 0,
    retain_payload TINYINT(1) NOT NULL DEFAULT 0,
    payload_expires_at DATETIME(3) NULL,
    resource_type VARCHAR(32) NOT NULL DEFAULT '',
    resource_id VARCHAR(64) NOT NULL DEFAULT '',
    conversation_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    final_attempt_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    cached_input_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_output_tokens BIGINT NOT NULL DEFAULT 0,
    usage_json JSON NULL,
    reserved_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    final_cost DECIMAL(20,8) NOT NULL DEFAULT 0,
    refunded_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    http_status BIGINT NOT NULL DEFAULT 0,
    error_type VARCHAR(64) NOT NULL DEFAULT '',
    error_code VARCHAR(128) NOT NULL DEFAULT '',
    error_message TEXT NULL,
    error_param JSON NULL,
    error_retryable TINYINT(1) NOT NULL DEFAULT 0,
    started_at DATETIME(3) NOT NULL,
    first_byte_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    ttft_ms BIGINT NOT NULL DEFAULT 0,
    client_disconnected TINYINT(1) NOT NULL DEFAULT 0,
    lease_owner VARCHAR(64) NOT NULL DEFAULT '',
    lease_expires_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_api_calls_request_id (request_id),
    KEY idx_api_calls_user_created (user_id, created_at),
    KEY idx_api_calls_token_created (token_id, created_at),
    KEY idx_api_calls_status_created (status, created_at),
    KEY idx_api_calls_endpoint (endpoint),
    KEY idx_api_calls_operation (operation),
    KEY idx_api_calls_model (model),
    KEY idx_api_calls_resource (resource_type, resource_id),
    KEY idx_api_calls_conversation_id (conversation_id),
    KEY idx_api_calls_final_attempt_id (final_attempt_id),
    KEY idx_api_calls_error_code (error_code),
    KEY idx_api_calls_created_at (created_at),
    KEY idx_api_calls_started_at (started_at),
    KEY idx_api_calls_updated_at (updated_at),
    KEY idx_api_calls_payload_expires_at (payload_expires_at),
    KEY idx_api_calls_lease_expires_at (lease_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_call_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    call_id VARCHAR(64) NOT NULL,
    attempt_no BIGINT NOT NULL,
    route_kind VARCHAR(24) NOT NULL DEFAULT 'gateway_v2',
    stage VARCHAR(24) NOT NULL DEFAULT '',
    ability_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    channel_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    key_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    endpoint_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    account_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    protocol VARCHAR(20) NOT NULL DEFAULT '',
    vendor_model VARCHAR(120) NOT NULL DEFAULT '',
    transport VARCHAR(64) NOT NULL DEFAULT '',
    request_path VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'started',
    http_status BIGINT NOT NULL DEFAULT 0,
    error_type VARCHAR(64) NOT NULL DEFAULT '',
    error_code VARCHAR(128) NOT NULL DEFAULT '',
    error_message TEXT NULL,
    error_retryable TINYINT(1) NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    cached_input_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_output_tokens BIGINT NOT NULL DEFAULT 0,
    usage_json JSON NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    ttft_ms BIGINT NOT NULL DEFAULT 0,
    provider_response_id VARCHAR(128) NOT NULL DEFAULT '',
    started_at DATETIME(3) NOT NULL,
    first_byte_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY idx_api_call_attempt_no (call_id, attempt_no),
    KEY idx_api_call_attempts_route_kind (route_kind),
    KEY idx_api_call_attempts_stage (stage),
    KEY idx_api_call_attempts_ability_id (ability_id),
    KEY idx_api_call_attempts_channel_id (channel_id),
    KEY idx_api_call_attempts_key_id (key_id),
    KEY idx_api_call_attempts_endpoint_id (endpoint_id),
    KEY idx_api_call_attempts_account_id (account_id),
    KEY idx_api_call_attempts_transport (transport),
    KEY idx_api_call_attempts_status (status),
    KEY idx_api_call_attempts_error_code (error_code),
    KEY idx_api_call_attempts_provider_response_id (provider_response_id),
    KEY idx_api_call_attempts_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_call_payloads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    call_id VARCHAR(64) NOT NULL,
    attempt_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    kind VARCHAR(32) NOT NULL,
    content_type VARCHAR(128) NOT NULL DEFAULT 'application/json',
    data LONGBLOB NULL,
    encrypted TINYINT(1) NOT NULL DEFAULT 0,
    truncated TINYINT(1) NOT NULL DEFAULT 0,
    original_bytes BIGINT NOT NULL DEFAULT 0,
    expires_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_api_call_payload_kind (call_id, kind),
    KEY idx_api_call_payloads_attempt_id (attempt_id),
    KEY idx_api_call_payloads_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
