// Package security contains the cryptographic primitives used by the unified
// gateway persistence layer. It has no database or configuration dependency.
package security

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"strconv"
)

const (
	EnvelopeVersion uint8 = 1
	KeySize               = 32
)

var (
	ErrInvalidKey      = errors.New("security: key must be 32 bytes")
	ErrInvalidEnvelope = errors.New("security: invalid encrypted envelope")
	ErrAuthentication  = errors.New("security: authentication failed")
	ErrInvalidAAD      = errors.New("security: invalid AAD binding")
)

// CanonicalAAD constructs the binding used by encrypted_blobs. Length prefixes
// make the encoding unambiguous even when owner bytes contain zeroes.
func CanonicalAAD(blobID uint64, purpose string, schemaVersion uint32, owner []byte) ([]byte, error) {
	if blobID == 0 || purpose == "" || len(owner) == 0 {
		return nil, ErrInvalidAAD
	}
	result := make([]byte, 0, 32+len(purpose)+len(owner))
	result = append(result, "prism-blob-aad-v1"...)
	var number [8]byte
	binary.BigEndian.PutUint64(number[:], blobID)
	result = append(result, number[:]...)
	binary.BigEndian.PutUint32(number[:4], uint32(len(purpose)))
	result = append(result, number[:4]...)
	result = append(result, purpose...)
	binary.BigEndian.PutUint32(number[:4], schemaVersion)
	result = append(result, number[:4]...)
	binary.BigEndian.PutUint32(number[:4], uint32(len(owner)))
	result = append(result, number[:4]...)
	result = append(result, owner...)
	return result, nil
}

// Envelope is the database-neutral representation of an encrypted blob.
// The data key is encrypted by the KEK; plaintext keys never belong in this
// structure or in a persistence model.
type Envelope struct {
	Version    uint8
	AADVersion uint16
	KEKVersion uint32
	Nonce      []byte
	Ciphertext []byte
	WrapNonce  []byte
	WrappedDEK []byte
}

// Seal creates a fresh data key and encrypts plaintext with AES-256-GCM.
// aad must be the canonical owner binding generated by the caller.
func Seal(plaintext, aad, kek []byte, kekVersion uint32) (Envelope, error) {
	if len(kek) != KeySize {
		return Envelope{}, ErrInvalidKey
	}
	dataKey := make([]byte, KeySize)
	if _, err := io.ReadFull(cryptorand.Reader, dataKey); err != nil {
		return Envelope{}, fmt.Errorf("generate data key: %w", err)
	}
	dataAEAD, err := newAEAD(dataKey)
	if err != nil {
		return Envelope{}, err
	}
	nonce := make([]byte, dataAEAD.NonceSize())
	if _, err := io.ReadFull(cryptorand.Reader, nonce); err != nil {
		return Envelope{}, fmt.Errorf("generate data nonce: %w", err)
	}
	ciphertext := dataAEAD.Seal(nil, nonce, plaintext, aad)

	kekAEAD, err := newAEAD(kek)
	if err != nil {
		return Envelope{}, err
	}
	wrapNonce := make([]byte, kekAEAD.NonceSize())
	if _, err := io.ReadFull(cryptorand.Reader, wrapNonce); err != nil {
		return Envelope{}, fmt.Errorf("generate wrap nonce: %w", err)
	}
	wrappedDEK := kekAEAD.Seal(nil, wrapNonce, dataKey, wrapAAD(aad, kekVersion))
	return Envelope{
		Version:    EnvelopeVersion,
		AADVersion: 1,
		KEKVersion: kekVersion,
		Nonce:      nonce,
		Ciphertext: ciphertext,
		WrapNonce:  wrapNonce,
		WrappedDEK: wrappedDEK,
	}, nil
}

// Open authenticates and decrypts an envelope with the KEK selected by its
// persisted version. The caller must select that version from the keyring.
func (e Envelope) Open(aad, kek []byte) ([]byte, error) {
	if e.Version != EnvelopeVersion || e.AADVersion != 1 || len(kek) != KeySize {
		return nil, ErrInvalidEnvelope
	}
	kekAEAD, err := newAEAD(kek)
	if err != nil {
		return nil, err
	}
	if len(e.WrapNonce) != kekAEAD.NonceSize() || len(e.WrappedDEK) < kekAEAD.Overhead() {
		return nil, ErrInvalidEnvelope
	}
	dataKey, err := kekAEAD.Open(nil, e.WrapNonce, e.WrappedDEK, wrapAAD(aad, e.KEKVersion))
	if err != nil {
		return nil, ErrAuthentication
	}
	if len(dataKey) != KeySize {
		return nil, ErrInvalidEnvelope
	}
	dataAEAD, err := newAEAD(dataKey)
	if err != nil {
		return nil, err
	}
	if len(e.Nonce) != dataAEAD.NonceSize() || len(e.Ciphertext) < dataAEAD.Overhead() {
		return nil, ErrInvalidEnvelope
	}
	plaintext, err := dataAEAD.Open(nil, e.Nonce, e.Ciphertext, aad)
	if err != nil {
		return nil, ErrAuthentication
	}
	return plaintext, nil
}

// HMACSHA256 returns a fixed-size digest for alias and integrity indexes.
func HMACSHA256(key, value []byte) [32]byte {
	mac := hmac.New(sha256.New, key)
	_, _ = mac.Write(value)
	var digest [32]byte
	copy(digest[:], mac.Sum(nil))
	return digest
}

func newAEAD(key []byte) (cipher.AEAD, error) {
	if len(key) != KeySize {
		return nil, ErrInvalidKey
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

func wrapAAD(aad []byte, kekVersion uint32) []byte {
	result := make([]byte, 0, len(aad)+16)
	result = append(result, "prism-wrap-v1\x00"...)
	result = append(result, aad...)
	result = append(result, 0)
	result = append(result, strconv.FormatUint(uint64(kekVersion), 10)...)
	return result
}
